---
- name: Install custom thrid party package for Synapse
  copy:
    src: "files/synapse-packages"
    dest: "{{ europython_synapse_packages_volume }}"
    backup: yes # just in case someone edited the files directly
